# Generated by Django 6.0.2 on 2026-03-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hero_delete_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('birthday', models.CharField(blank=True, max_length=50)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(blank=True, max_length=10)),
                ('degree', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('freelance', models.CharField(blank=True, max_length=50)),
                ('skill_html', models.IntegerField(default=0)),
                ('skill_css', models.IntegerField(default=0)),
                ('skill_js', models.IntegerField(default=0)),
                ('skill_php', models.IntegerField(default=0)),
                ('skill_wordpress', models.IntegerField(default=0)),
                ('skill_photoshop', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
