# Generated by Django 6.0.2 on 2026-03-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='A108 Adam Street, New York, NY 535022', max_length=255)),
                ('phone', models.CharField(default='+1 5589 55488 55', max_length=50)),
                ('email', models.EmailField(default='info@example.com', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
