# Generated by Django 6.0.2 on 2026-03-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('degree', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('start_year', models.CharField(blank=True, max_length=10)),
                ('end_year', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('education', 'Education'), ('experience', 'Experience')], max_length=50)),
            ],
        ),
    ]
