# Generated by Django 6.0.2 on 2026-03-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_aboutsection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='subtitle',
            field=models.CharField(max_length=500),
        ),
    ]
